### PR TITLE
Fix PHPcs baseline test failure when there are no files to check

### PR DESCRIPTION
**Pull request by Tjitse-E**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/mage-os/github-actions/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
Currently the PHPCS baseline tests are failing when there are no files to check. See https://github.com/mage-os/mageos-magento2/actions/runs/5794755408/job/15940229468?pr=32.

## What is the new behavior?
- Stop before `composer install` step when phpcs has no files to check
- Only run phpcs for files in the app dir
- Simplify action, by utilising the build in function of [tj-actions/changed-files](https://github.com/tj-actions/changed-files) to check which files were modified.
- Trigger error when phpcs baseline was not created.
- Run phpcs on all filetypes that  are specified in the [Magento ruleset](https://github.com/magento/magento-coding-standard/blob/develop/Magento2/ruleset.xml#L5-L6)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Additional information
- [Example run](https://github.com/Tjitse-E/mageos-magento2/actions/runs/6110014181/job/16582167594) with adding an additional error in `app/code/Magento/Catalog/view/frontend/templates/product/breadcrumbs.phtml`, while there are existing errors in breadcrumbs.phtml (that are now in the baseline, so shoudn't be reported).
- [Example run](https://github.com/Tjitse-E/mageos-magento2/actions/runs/6110345217/job/16583150086) when there are no relevant phpcs files changed.

## Related PR
https://github.com/mage-os/mageos-magento2/pull/32

### CODE REVIEW

**Comment by Tjitse-E** [comment]
@Vinai  you can see the baseline in action here https://github.com/mage-os/mageos-magento2/pull/34. I've ran the baseline tests on https://github.com/mage-os/mageos-magento2/pull/21

**Comment by Tjitse-E** [comment]
@Vinai  i've resolved the issue that occured last friday (the baseline test didn't work on forked repo's). We now have a successfull run: https://github.com/mage-os/mageos-magento2/actions/runs/6149981258/job/16686980485?pr=34.

**Comment by Vinai** [comment]
Thank you, I will review!
Can you join us today at 3pm CET for the weekly tech meeting by chance?
It's in the voice channel on Discord.

**Review by Vinai — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
